### ISSUE TITLE
有使用教程吗？

### ISSUE THREAD

**Issue by murrayee** [bozaigao/react-native-refresh-loadmore-recyclerlistview#1]
没找到下拉刷新的那个demo呢

**Comment by bozaigao** [comment]
demo我晚点传上去，使用方法很简单，只需要在recyclerview的使用基础上在组件属性增加onRefresh和onEndReached方法就行，没有这两个方法的话就默认没有下拉刷新和上拉加载，同时自己根据调用时机调用this.组件ref.onRefreshEnd()、this.组件ref.onRefreshEnd()、this.组件ref.onNoDataToLoad()这三个函数

**Comment by bozaigao** [comment]
@murrayee demo我晚点传上去，使用方法很简单，只需要在recyclerview的使用基础上在组件属性增加onRefresh和onEndReached方法就行，没有这两个方法的话就默认没有下拉刷新和上拉加载，同时自己根据调用时机调用this.组件ref.onRefreshEnd()、this.组件ref.onRefreshEnd()、this.组件ref.onNoDataToLoad()这三个


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by murrayee** [comment]
> @murrayee demo我晚点传上去，使用方法很简单，只需要在recyclerview的使用基础上在组件属性增加onRefresh和onEndReached方法就行，没有这两个方法的话就默认没有下拉刷新和上拉加载，同时自己根据调用时机调用this.组件ref.onRefreshEnd()、this.组件ref.onRefreshEnd()、this.组件ref.onNoDataToLoad()这三个函数

支持自定义indicator吗  看起来很nice。谢谢哈
